site_name: Spoofax
site_author: Spoofax Team
site_description: Spoofax language workbench
site_url: https://www.spoofax.dev/

copyright: "Copyright &copy; 2010-2021 Spoofax Team"

repo_name: spoofax
repo_url: https://github.com/metaborg/spoofax
edit_uri: https://github.com/metaborg/metaborg.github.io/edit/main/docs

nav:
  - Home:
    - index.md
    - getting-started.md
  - Tutorials:
    - tutorials/index.md
  - How-Tos:
    - howtos/index.md
    - Installation:
      - howtos/installation/install-eclipse-bundle.md
      - howtos/installation/install-eclipse-plugin-manually.md
      - howtos/installation/install-from-source.md
    - Static Semantics:
      - howtos/statix/debugging.md
      - howtos/statix/migrating-from-nabl2.md
      - howtos/statix/migrating-to-concurrent-solver.md
    - Transformation:
      - howtos/stratego/generate-signature.md
      - howtos/stratego/run-stratego-programs.md
      - howtos/stratego/generate-pretty-printer.md
      - howtos/stratego/debug-stratego.md
      - howtos/stratego/concrete-syntax.md
      - howtos/stratego/exchange-terms.md
      - howtos/stratego/inspect-terms.md
    - Editor Services:
      - howtos/editor-services/rename-refactoring.md
    - Development:
      - howtos/development/index.md
      - Requirements: howtos/development/requirements.md
      - Maven: howtos/development/maven.md
      - Building: howtos/development/building.md
      - Developing: howtos/development/developing.md
      - Releasing: howtos/development/releasing.md
      - Troubleshooting: howtos/development/troubleshooting.md
  - References:
    - references/index.md
    - Configuration:
      - references/config/index.md
    - Syntax:
      - references/syntax/index.md
      - references/syntax/modules.md
      - references/syntax/symbols.md
      - references/syntax/productions.md
      - references/syntax/lexical-syntax.md
      - references/syntax/context-free-syntax.md
      - references/syntax/kernel-syntax.md
      - references/syntax/start-symbols.md
      - references/syntax/templates.md
      - references/syntax/disambiguation.md
      - references/syntax/layout-sensitivity.md
      - references/syntax/recovery.md
      - references/syntax/configuration.md
    - Static Semantics:
      - references/statix/index.md
      - references/statix/concepts.md
      - references/statix/modules.md
      - references/statix/terms.md
      - references/statix/basic-constraints.md
      - references/statix/rules.md
      - references/statix/scope-graphs.md
      - references/statix/queries.md
      - references/statix/tests.md
      - references/statix/stratego-api.md
    - Data Flow Analysis:
      - references/flowspec/introduction.md
      - references/flowspec/structure.md
      - references/flowspec/Stratego_API.md
      - references/flowspec/configuration.md
      - references/flowspec/testing.md
      - references/flowspec/references.md
    - Transformation:
      - references/stratego/index.md
      - references/stratego/lexical.md
      - references/stratego/modules.md
      - references/stratego/terms.md
      - references/stratego/types.md
      - references/stratego/rewrite-rules.md
      - references/stratego/strategy-definitions.md
      - references/stratego/strategy-combinators.md
      - references/stratego/dynamic-rules.md
      - Troubleshooting: references/stratego/troubleshooting.md
    - Testing:
      - references/testing/index.md
      - references/testing/test-suites.md
      - references/testing/test-expectations.md
      - references/testing/running-tests.md
    - Editor Services:
      - references/editor-services/index.md
      - references/editor-services/esv.md
      - references/editor-services/analysis.md
      - references/editor-services/file-extensions.md
      - references/editor-services/hover.md
      - references/editor-services/menus.md
      - references/editor-services/on-save.md
      - references/editor-services/outline.md
      - references/editor-services/parsing.md
      - references/editor-services/reference-resolution.md
      - references/editor-services/renaming.md
      - references/editor-services/stratego.md
      - references/editor-services/syntax-highlighting.md
    - Pipelines:
      - references/pipelines/index.md
      - references/pipelines/modules.md
      - references/pipelines/types.md
      - references/pipelines/generics.md
      - references/pipelines/functions.md
      - references/pipelines/expressions.md
  - Background:
    - background/index.md
    - Bibliography:
      - background/bibliography/index.md
      # - background/bibliography/references.md
      - background/bibliography/sdf3.md
      - background/bibliography/statix.md
      - background/bibliography/stratego.md
    - Static Semantics:
      - background/statix/index.md
    - Transformations:
      - background/stratego/index.md
      - Strategic Rewriting:
        - background/stratego/strategic-rewriting/term-rewriting.md
        - background/stratego/strategic-rewriting/limitations-of-rewriting.md
        - background/stratego/strategic-rewriting/traversal-with-rules.md
        - background/stratego/strategic-rewriting/strategic-rewriting.md
      - Strategy Combinators:
        - background/stratego/strategy-combinators/sequential.md
        - background/stratego/strategy-combinators/term.md
        - background/stratego/strategy-combinators/traversal.md
        - background/stratego/strategy-combinators/type-unifying.md
    - Documentation:
      - background/documentation/index.md
      - Adding Pages: background/documentation/pages.md
      - Links: background/documentation/links.md
      - GUIs and Menus: background/documentation/guis-and-menus.md
      - Citations: background/documentation/citations.md
      - Structure: background/documentation/structure.md
      - Troubleshooting: background/documentation/troubleshooting.md
  - Support:
    - support/index.md
    - support/contributions.md
  - Releases:
    - release/stable.md
    - release/develop.md
    - Release Notes:
      - release/note/2.5.16.md
      - release/note/2.5.15.md
      - release/note/2.5.14.md
      - release/note/2.5.13.md
      - release/note/2.5.12.md
      - release/note/2.5.11.md
      - release/note/2.5.10.md
      - release/note/2.5.9.md
      - release/note/2.5.8.md
      - release/note/2.5.7.md
      - release/note/2.5.6.md
      - release/note/2.5.5.md
      - release/note/2.5.4.md
      - release/note/2.5.3.md
      - release/note/2.5.2.md
      - release/note/2.5.1.md
      - release/note/2.5.0.md
      - release/note/2.4.1.md
      - release/note/2.4.0.md
      - release/note/2.3.0.md
      - release/note/2.2.1.md
      - release/note/2.2.0.md
      - release/note/2.1.0.md
      - release/note/2.0.0.md
      - release/note/2.0.0-beta1.md
      - release/note/1.5.0.md
      - release/note/1.4.0.md
      - release/note/1.3.1.md
      - release/note/1.3.0.md
      - release/note/1.2.0.md
      - release/note/1.1.0.md
      - release/note/1.0.2.md
      - release/note/1.0.0.md
      - release/note/vnext.md
    - Migration Guides:
      - release/migrate/2.5.15.md
      - release/migrate/2.5.10.md
      - release/migrate/2.5.5.md
      - release/migrate/2.1.0.md
      - release/migrate/2.0.0.md
      - release/migrate/march2016_project_structure.md
      - release/migrate/vnext.md

theme:
  name: material
  custom_dir: overrides
  language: en
  logo: assets/logo.svg
  favicon: assets/favicon.png
  icon:
    logo: fontawesome/solid/sticky-note
    repo: fontawesome/brands/github
  palette:
    # Light mode
    - media: "(prefers-color-scheme: light)"
      scheme: spoofax
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
    # Dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode
  font:
    code: JetBrains Mono
  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.top
    - navigation.indexes

extra_css:
  - assets/styles.css
extra_javascript:
  - assets/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js


markdown_extensions:
  - abbr
  - admonition
  - attr_list
  - def_list
  - footnotes
  - toc:
      permalink: true
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.highlight:
      guess_lang: false
  - pymdownx.inlinehilite:
      custom_inline:
        - name: gui
          class: guilabel
          format: !!python/name:formatters.inline_span_format
  - pymdownx.keys:
      key_map:
        click: "Click"
        left-click: "Left Click"
        right-click: "Right Click"
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.saneheaders
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tabbed
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde

plugins:
  - search
  - git-revision-date:
      enabled_if_env: CI
  - macros:
      module_name: tools/macro
      include_dir: include
  - bibtex:
      bib_dir: "bibliographies"
      cite_style: "pandoc"
